## Check resolving hostname via  DNS
---
- hosts: all

#  roles:
#    - akirak.coreos-python

  become: yes

  tasks:
  - name: Check host name resolve
    shell: host $(hostname)
    register: output
    failed_when: "output.rc != 0"
