## Checking XFS FSTYPE for docker storage
---
- hosts: all

  roles:
    - akirak.coreos-python

  become: yes

  vars_files:
   - ../vars/globals.yml

  tasks:
  - name: Check directory type
    stat:
       path: "{{ docker_storage }}"
    register: docker_dir

  - name: Populate Variable via Shell Command
    shell: lsblk -f $(df -P /var/lib/docker|tail -1|cut -d' ' -f 1)|tail -1
    register: dockertype
    ignore_errors: True

  - name: Validate docker directory fstype
    shell: echo "ERROR {{ docker_storage }} filesystem is '{{ dockertype.stdout }}'. It should be a XFS filesystem."
    register: output
    failed_when: "'xfs' not in dockertype.stdout"
