## Checking maximum number of open files on compute node

---
- hosts: all
  gather_facts: yes

#  roles:
#    - akirak.coreos-python

  tasks:
  - name: Populate max_num_process Variable
    shell: ulimit -u
    register: max_num_process

  - debug:
      var: max_num_process.stdout

  - name: Check Maximum Number of processes on compute node
    shell: echo "Max number of processes setting is not configured correctly."
    register: output
    failed_when: max_num_process.stdout|int < 12288
