- hosts: all
  gather_facts: yes

#  roles:
#    - akirak.coreos-python

  tasks:
  - name: Check Processor Type
    shell: echo "Error Processor type must be x86_64 or ppc64"
    register: output
    failed_when: ansible_architecture != "x86_64" and ansible_architecture != "ppc64"

  - debug:
      var: ansible_architecture
