## Checking cri_o version

---
- hosts: all
  gather_facts: yes

  roles:
    - akirak.coreos-python

  tasks:
  - name: Populate Variable
    shell: crio --version
    register: version

  - debug:
      var: version.stdout

  - name: Check cri-o Version
    shell: grep -Eo '1\.[0-9]{1,2}' <<< "{{ version.stdout }}"
    register: output
    failed_when: output.stdout | version_compare('1.13', '<')

  - debug:
      var: output.stdout

