## Checking openshift version

---
- hosts: all
  gather_facts: yes

  roles:
    - akirak.coreos-python

  tasks:
  - name: Populate Variable
    shell: oc version
    register: version

  - debug:
      var: version.stdout

  - name: Check Openshift Version
    shell: grep -Eo '(3\.11|4\.3)' <<< "{{ version.stdout }}"
    register: output
    failed_when: output.stdout != "3.11" and output.stdout != "4.3"
  
  - debug:
      var: output.stdout
