## Checking subnet

---

- hosts: all
  gather_facts: yes

  roles:
    - akirak.coreos-python

  vars:
    ip_addr: "{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}"
    test: "{{ ip_addr | ipaddr }}"
  tasks:
    - debug:
        var: ip_addr

    - name: Check subnet mask
      shell: ip addr show | grep -o {{ ip_addr }}/[0-9]*
      register: ip_slash
    - debug:
        var: ip_slash.stdout

