## Checking maximum number of queue identifiers on compute node

---
- hosts: all
  gather_facts: yes

  roles:
    - akirak.coreos-python

  tasks:
  - name: Populate msg_mni Variable
    shell: sysctl kernel.msgmni
    register: msg_mni

  - debug:
      var: msg_mni.stdout

  - name: Check Maximum Number of Queue Identifiers
    shell: grep -Eo [0-9]* <<< "{{ msg_mni.stdout }}"
    register: output2
    failed_when: output2.stdout < 32768
