## Checking openshift version

---
- hosts: all
  gather_facts: yes

  roles:
    - akirak.coreos-python

  tasks:
  - name: Populate Variable
    shell: oc version
    register: version

  - debug:
      var: version.stdout

  - name: Check Openshift Version on Ansible 2.4-
    shell: grep -Eo '(4\.3\.[0-9]*)' <<< "{{ version.stdout }}"
    register: output
    failed_when: output.stdout | version_compare("4.3.13", "<")
    ignore_errors: yes  

  - debug:
      var: output.stdout

  - name: Check Openshift Version on Ansible 2.5+
    shell: echo "This test should work if the previous test failed due to an older ansible version installation."
    failed_when: output.stdout is version('4.3.13', '<')
    ignore_errors: yes
